

eureka:
  instance:
    prefer-ip-address : true
  client:
    service-url:
      fetch-ragistry: true
      default-zone: http://localhost:8761/eureka


  spring:
    application:
     name: trs-SERVICE
